language: julia
os:
    - osx
    - linux
julia:
    - release
    - nightly
notifications:
    email: false
env:
    script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd()); Pkg.build("Ogre"); Pkg.test("Ogre"; coverage=true)';
    - julia -e 'cd(Pkg.dir("Ogre")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
